### ISSUE TITLE
2 things i found

### ISSUE THREAD

**Issue by FozzySf5** [overextended/ox_inventory#1142]
1. when around people or alot of people, the inventory stops working and it says u cant use the inventory
2. when in inventory, you can still look around and punch players near you.

and i still dont know how to use the special mk2 ammo after couple of back updates

i have no way of remaking the bug but both bugs get us killed in the city.

**Comment by thelindat** [comment]
wow very cool!!

**Comment by FozzySf5** [comment]
> wow very cool!!
very cool what? i have inventory bugs i found...its just happened now. can we please fix it?

**Comment by thelindat** [comment]
You have claims of inventory bugs that nobody else has, have no steps for me to reproduce them, have provided no information about the resources running on your server, and have made no attempt to debug them yourself (as they occur on _your_ server, not others).

Being unable to use your inventory when "around people" makes no sense and just sounds like some stupid assumption you've made (as people always do) - you could of course _look into that_ but you didn't.

Being able to look around and punch people while the inventory is open is some resource conflict and I don't know what you expect me to do for that. https://github.com/overextended/ox_inventory/blob/main/client.lua#L1284-L1290

**Comment by FozzySf5** [comment]
you can be less a ass about it. it happens to me and others in the server. And i have tryed to look i to it. no errors that i see. if i provide u with clips, then what? i just do wish i would not be so rude to people when your customers are helping u find bugs.

 i would be cool even with a lie. "ill look into it, thank you"

**Comment by thelindat** [comment]
> it happens to me and others in the server.

Yes, on your server, not on the other >1000 servers.

> your customers

noun
a person who purchases goods or services from another; buyer; patron.

> helping u find bugs.

A server running a resource that conflicts with the inventory isn’t a bug, nor something I can do anything about.

> i would be cool even with a lie. "ill look into it, thank you"

Why would I lie? Would lying to everybody somehow make me a better person than just stating the facts? You want me to spare peoples feelings rather than have them confront the truth? Want me to act polite and giving you false hope then giggle about you in a private channel somewhere?
