### ISSUE TITLE
Remove a bulletproof or parachute

### ISSUE THREAD

**Issue by Bulle93230** [overextended/ox_inventory#1190]
Hi, is it possible to add a button in the inventory to remove a bulletproof and a parachute if equipped ? (or something else)
And for bulletproof maybe if you took damages it durability is lower and the next time you'll equip it, it will give less armor ? :)
Thank you for you work !

**Comment by jnccloud** [comment]
I feel like this is going too far for what the inventory should do. You could create logic using events in your items.lua that do something like:

- When armor is equipped, insert a new item to the player's inventory like "Equipped Plates", trigger a durability loss in the item that corresponds to the UI for the amount of armor lost. When the armor is 0 - either delete it or convert it to damaged plates so that they can be recycled or whatever other usecase you can find.
- For the parachute, insert a new item such as "Parachute Bag" that will swap back to the parachute after it's been taken off the player. If the player has a parachuting accident you can just delete the bag or swap it to a "Ripped backpack" type item for recycling.

These can be done by modifying your armor and parachute scripts to update the items/inventory as needed. Because of the variability in armor and parachutes between frameworks and even individual servers, it doesn't make sense to _me_ to include it in the inventory system.
