### ISSUE TITLE
Double click to use item

### ISSUE THREAD

**Issue by Manason** [overextended/ox_inventory#1263]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Nice UX enhancement, double click to use an item rather than having to right click and select use.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LukeWasTakenn** [comment]
ctrl + click is already a thing for fast use, why have 2 fast use binds?

**Comment by jag3dagster** [comment]
Doesn't ctrl + click just move an item to the opposite inventory side, not use it?

**Comment by jag3dagster** [comment]
oh alt + click is use

**Comment by Manason** [comment]
Well people are used to double click because of qb-inventory, and I also think double left click is intuitive for using items in an inventory as many games follow the pattern.

**Comment by thelindat** [comment]
>because of qb-inventory

That's just a shortcut to getting anything disapproved.

> double left click is intuitive for using items in an inventory as many games follow the pattern

I dislike games with double left-click to use when click is also dragging, preferring a right-click pattern (also common); but since that brings up a tooltip we obviously can't do that.

There are 4 methods of using items right now and little need for another (or to change the bindings).
- alt+click
- right-click and click use
- drag to use
- hotkey
