### ISSUE TITLE
Use Qwik instead of React

### ISSUE THREAD

**Issue by CoachYT1** [overextended/ox_inventory#1330]
**Is your feature request related to a problem? Please describe.**
This feature requests is not related to a problem but could improve UI performance

**Describe the solution you'd like**
Qwik allows you to bypass hydration and generate pure HTML and sends JS files only when needed, resulting in improved performance.

**Describe alternatives you've considered**
One alternative I've considered is to stick with React, but I'm just asking if using Qwik could improve performance.

**Additional context**
If necessary, I can try to help migrate to Qwik via a pull request.

**Comment by LukeWasTakenn** [comment]
You can't use ssr in cef.

**Comment by CoachYT1** [comment]
https://qwik.builder.io/docs/guides/static-site-generation/

You can generate the HTML at build time, so SSR is not required.

**Comment by thelindat** [comment]
I’m not a web dev so you’re going to have to dumb this down.

How does one pre-render dynamic inventories with potentially 1000 slots which can contain any number of stackable and moveable items?

Furthermore, the server that is hosting the content is already local - ran on the clients machine; there is no benefit to reducing client-server traffic because they already download everything with the resource anyway.

Swapping to Qwik doesn’t seem like it would provide much (if any) benefit. The current plan was to swap to SolidJS for 3.0.
