### ISSUE TITLE
Inventories not saving on server restart

### ISSUE THREAD

**Issue by Smailas01** [overextended/ox_inventory#1430]
**Describe the bug**
Item duplication

**Framework**
ESX

**Resource version**
2.32.1

**Expected behavior**
You put a item in stash like weapon or money then you take it from stash that item you used money to buy car and after server restart 
money will be back to that same stash. (Item duplication)

**Comment by MatinHQ** [comment]
Do you use `saveinv` command before restarting server?

**Comment by Smailas01** [comment]
> Do you use `saveinv` command before restarting server?

its not using automatic ? If its not so no im not.

**Comment by thelindat** [comment]
As always, I do not have access to your server. If something cannot be reproduced on my test servers, I cannot take any action; unless any actual information can be given to explain how the resource is not saving.

Note that saves are automatically triggered when all players have left the server, or with the shuttingDown txAdmin event (scheduled and unscheduled restarts); otherwise they occur every 5 minutes.

**Comment by Smailas01** [comment]
in database inventory not updating users stashs i just saw that...  with older version of ox inventory it was all good

**Comment by thelindat** [comment]
That's cool now provide information that I can use to reproduce and then solve it instead of repeating the same thing.

**Comment by patriotgaming** [comment]
im having this same issue. Your saying to provide information to reproduce it. But thats the thing, we dont know how to reproduce it because not only is it random, it affects random players. Ive gone through the database to see if anything was wrong i tried my own trouble shooting. This was not happening until i updated ox inventory recently (had to due to a script that required it) Every day its new people losing stashes, trunks, or the ox stashes in the quasar housing. Ive looked through issues and seen many others are having the same issue. We never do nothing but scheduled server restarts. We are not gonna do the saveinv command every scheduled restart because 1 it should auto trigger and 2 our restarts are when no one is awake. This issue is one of the biggest issues we have right now and i am willing to provide any information to help solve this issue. I understand as a developer it is hard to fix something you can not reproduce, but please instead of saying we are not giving enough information, try to assist further. We are proving all the information we have to you

**Comment by patriotgaming** [comment]
I can send one of my tables of the players that have been affected of you like, but not much else i think i can really provide to help you besides explaining what happens

**Comment by thelindat** [comment]
> we dont know how to reproduce it because not only is it random, it affects random players

and I'm supposed to resolve something that is "random", affects "random players" and cannot be reproduced on my own?

> This was not happening until i updated ox inventory recently

People were complaining about saving issues _months ago_. So I refactored saving and _more people are complaining_. Yet there's still nothing that I can find to change aside from completely overhauling (and breaking) how inventories are saved - which I can't do.

> Ive looked through issues and seen many others are having the same issue

Except most of those reports were invalid or resolved.

> We are not gonna do the saveinv command every scheduled restart because 1 it should auto trigger

It literally fucking does.

https://github.com/overextended/ox_inventory/blob/f0dcd328f04cfdb2e3eafbf40dfef756fbe39248/modules/inventory/server.lua#L2248-L2262

> try to assist further

I cannot. Every change I have attempted to resolve this yet-to-be-reproduced-issue has resulted in _more people_ complaining that saving doesn't work.

**Comment by luthanirgi** [comment]
happens to me as well, the last thing i do is delete some items on items.lua.
here is the log for that.
```
[ script:ox_inventory] [91mSCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:65: attempt to index a nil value (field '?')
[ script:ox_inventory] > ref (@monitor/resource/sv_main.lua:299)
[      script:monitor] [txAdmin] Server shutdown imminent. Kicking all players.
```
and i'm added some code for adding backup save, not sure this is will working or no xD
```
AddEventHandler('txAdmin:events:scheduledRestart', function(eventData)
	if eventData.secondsRemaining == 60 then
	  CreateThread(function()
		Wait(50000)
		Inventory.SaveInventories(true)
	  end)
	end
end)
```

**Comment by thelindat** [comment]
> [ script:ox_inventory] �[91mSCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:65: attempt to index a nil value (field '?')
> [ script:ox_inventory] > ref (@monitor/resource/sv_main.lua:299)
> [      script:monitor] [txAdmin] Server shutdown imminent. Kicking all players.

Weird trace but assuming line 65 references the same as the source code.

```lua
function OxInventory:syncSlotsWithClients(slots, syncOwner)
	for playerId in pairs(self.openedBy) do
		if self.id ~= playerId then
			TriggerClientEvent('ox_inventory:updateSlots', playerId, slots, Inventories[playerId].weight) -- L65
		end
	end

	if syncOwner and self.player then
		TriggerClientEvent('ox_inventory:updateSlots', self.id, slots, self.weight)
	end
end
```

Might be an issue where an inventory isn't cleared from the openedBy table.

**Comment by patriotgaming** [comment]
> > we dont know how to reproduce it because not only is it random, it affects random players
> 
> and I'm supposed to resolve something that is "random", affects "random players" and cannot be reproduced on my own?
> 
> > This was not happening until i updated ox inventory recently
> 
> People were complaining about saving issues _months ago_. So I refactored saving and _more people are complaining_. Yet there's still nothing that I can find to change aside from completely overhauling (and breaking) how inventories are saved - which I can't do.
> 
> > Ive looked through issues and seen many others are having the same issue
> 
> Except most of those reports were invalid or resolved. So your many is more like 5 people.
> 
> > We are not gonna do the saveinv command every scheduled restart because 1 it should auto trigger
> 
> It literally fucking does.
> 
> https://github.com/overextended/ox_inventory/blob/f0dcd328f04cfdb2e3eafbf40dfef756fbe39248/modules/inventory/server.lua#L2248-L2262
> 
> > try to assist further
> 
> I cannot. Every change I have attempted to resolve this yet-to-be-reproduced-issue has resulted in _more people_ complaining that saving doesn't work.

Brother there is no reason to get upset. This is upsetting us just as much as it upsets you that you cannot reproduce it. We are not trying to be assholes. I love ox inventory which is why I haven’t switched. Instead of us always repeating ourselves, why don’t we somehow all come together (meaning people having the same issue) see what we have In common between our servers and try to figure it out. Maybe even making a discord channel in the overextended discord just for people with this issue to figure out would even be helpful

**Comment by patriotgaming** [comment]
> > [ script:ox_inventory] �[91mSCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:65: attempt to index a nil value (field '?')
> > [ script:ox_inventory] > ref (@monitor/resource/sv_main.lua:299)
> > [      script:monitor] [txAdmin] Server shutdown imminent. Kicking all players.
> 
> Weird trace but assuming line 65 references the same as the source code.
> 
> ```lua
> function OxInventory:syncSlotsWithClients(slots, syncOwner)
> 	for playerId in pairs(self.openedBy) do
> 		if self.id ~= playerId then
> 			TriggerClientEvent('ox_inventory:updateSlots', playerId, slots, Inventories[playerId].weight) -- L65
> 		end
> 	end
> 
> 	if syncOwner and self.player then
> 		TriggerClientEvent('ox_inventory:updateSlots', self.id, slots, self.weight)
> 	end
> end
> ```
> 
> Might be an issue where an inventory isn't cleared from the openedBy table.

I would literally PAY you to fix it

**Comment by CsyonDerEchte** [comment]
I reported this issue like a year ago on the ox discord. I even did a pullrequest but it got rejected. The problem is, that you have like 10 seconds to put your items into the stashes bevor restarting to dupe it. Thats my fix i did to prevent this issue:

AddEventHandler('txAdmin:events:scheduledRestart', function(eventData)
    if eventData.secondsRemaining == 60 then
        SetTimeout(50000, function()
            GlobalState.CanUseInventories = false
            saveInventories()
        end)
    end
end)

**Comment by thelindat** [comment]
Inventories are _already_ blocked from use when saving. You also aren't doing _anything_ different than what the restart event handler does - gives roughly 10 seconds notice. The scheduled restart event was _also_ added back in with a minute notice. There is _also_ a save once all players leave the server.

The problem isn't "the last 10 seconds", _they aren't saving at all after several hours_.

**Comment by CsyonDerEchte** [comment]
Sry i mean i blocked it for 10 seconds before the server restarts. Yes the inventory gets blocked if it saves but after the save you can still put stuff into a stash.  Atm it looks like you try to save it exactly on the restart and this could be the issue, because the server has no time to save it. And thats why i block the inventory for the last 10 seconds before the restart so i can save the inventory right there. :)

**Comment by thelindat** [comment]
> the inventory gets blocked if it saves but after the save you can still put stuff into a stash.

You _can't_. Because it gets set as _locked_ by both scheduledRestart and shuttingDown event handlers.

> it looks like you try to save it exactly on the restart and this could be the issue

No, because serverShuttingDown is not triggered "exactly on the restart" and gives 5 seconds in advance; and I don't know if you know how quick sending the queries to MySQL is.

> Atm you use

https://github.com/overextended/ox_inventory/blob/1a90dea4b86b370317b09cd21c9155f5c0ea3a5b/modules/inventory/server.lua#L2281C1-L2308C5

On top of this it saves _every 5 minutes_. Now please explain to me why you're bitching about "ThE LAsT TEn SEcOndS" when people are complaining about inventories not saving _at all_ after _6 hours_.

**Comment by CsyonDerEchte** [comment]
Im not bitching around just sharing my fix i did a year ago.

Sry the topic ist still duplicating Items because of "Inventories not saving ON SERVER RESTART"
The "not saving for 6 hours" should be another topic.
