### ISSUE TITLE
Set degradation via metadata & Status, Prop, Animation via metadata

### ISSUE THREAD

**Issue by benzon** [overextended/ox_inventory#1602]
**Usecase**
The reason for requesting this feature, is actually that with a feature like this, we could avoid having to create multiple food/drink items in the config file, and could potentially make on-the-fly recipes, for new foods or drinks.

This would require, that it’s possible to set status array, props, animation, and durability via metadata, that way one item can become an infinite amount of food/drink, or even other items, based on metadata.

**Potential Issues**
Would this have a negative impact on performance?

Would there be any other issues that would make this approach unsafe to use?

**Comment by thelindat** [comment]
You can just manually handle statuses, progressbar, etc. in your own resource rather than storing large amounts of data on individual items. Internal handling of such things is honestly legacy features at this point and too restrictive.

Either the item callbacks or just usedItem event.
https://github.com/overextended/ox_inventory/blob/main/client.lua#L429-L439
