### ISSUE TITLE
Crafting Leveling Based

### ISSUE THREAD

**Issue by kuomars110** [overextended/ox_inventory#1642]
Is your feature request related to a problem? Please describe.
No its not

Describe the solution you'd like
Ok crafting tables must have Level required , So for example if user want to craft a water he/she should have level2,
and for every item he/she craft it should be an XP reward so help him/her for leveling up

**Comment by tom-osborne** [comment]
Title unclear. If you are trying to request a feature at least use the provided template...



**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by kuomars110** [comment]
> Title unclear. If you are trying to request a feature at least use the provided template...
> 
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Ok I made it clear now

**Comment by Demigod916** [comment]
Seems like something that could be made externally outside of the inventory.
