### ISSUE TITLE
Glovebox vulnerability

### ISSUE THREAD

**Issue by Dennis-NL** [overextended/ox_inventory#1817]
### Summary
Players with mod menus can teleport into a car and steal items from the glovebox.

To prevent this, access to the glovebox should only be allowed when the car is unlocked. This might be the best way to protect it.

Consider locking the glovebox in the same way as the trunk.

Unfortunately, this is currently a significant problem.

### Details
With a mof menu you can teleport into locked cars. And steal stuff out of the glovebox

### PoC
Use mod menu to teleport into car, then open glovebox and steal stufd

### Impact
Big, people constantly losing glovebox items.

**Comment by thelindat** [comment]
> Players with mod menus can teleport into a car and steal items from the glovebox.
> Unfortunately, this is currently a significant problem.

Players being inside a vehicle and using a glovebox isn't a problem or vulnerability.

> To prevent this, access to the glovebox should only be allowed when the car is unlocked.

There are many instances where people drive around in locked vehicles - it makes no sense to prevent glovebox access. Furthermore, uh, your cheaters can just unlock any vehicle.

**Comment by Dennis-NL** [comment]
Thats not true, they cannot unlock it. Atleast if you use a good script or make your own

They cannot acces the trunk, but they can acces the glovebox because its does not lock.

So it is a problem

**Comment by thelindat** [comment]
> Thats not true, they cannot unlock it. Atleast if you use a good script or make your own
>
> They cannot acces the trunk

Why would they not be able to access the trunk when it's only locked using the game's native lock system? They can change that lock status exactly the same way as they teleport into a vehicle.

If using a custom non-native lock system, ox_inventory does not know about that system and still simply checks the lock status. Nothing about trunk access is secure, because it cannot be secure. Making gloveboxes check the lock status resolves absolutely nothing.

If you want to strengthen these systems then you need to use the openInventory event hook to disallow access on the server. No amount of client-side security is going to resolve the problem you're having.

**Comment by Dennis-NL** [comment]
Why be so ignorant about it?

I am using my own lock systen that uses the native locks. And there is no way to unlock it if you do not ownt that vehicle. Adding a lock to the glovebox will resolve this issue for many. You can atleast make it an option

**Comment by thelindat** [comment]
- client-side security is the same as no security
- gta5 is controlled entirely on the client
- clients can do anything they like, whenever they like
- lock status means nothing, because clients can change the lock status at will
- you are an ignoramus

Your "solution" to this "problem" makes no sense. It isn't fixing anything, just making gloveboxes and lock systems a complete nightmare to user experiences. Let's say we add a check for locks to the glovebox, cheaters now
- teleport into a vehicle using SetPedIntoVehicle, or TaskEnterVehicle, or whatever else
- unlock the vehicle using SetVehicleDoorsLocked
- wow they can open the glovebox huge exploit why is ox_inventory so shit bro

**Comment by Mycroft-Studios** [comment]
> that uses the native locks.
you mean, natives that the client can trigger whenever they want?

**Comment by Dennis-NL** [comment]
No they cant, our locksystem has a check in place
