### ISSUE TITLE
Durability on items, not just weapons

### ISSUE THREAD

**Issue by benzon** [overextended/ox_inventory#346]
Idea is very simple, add durability on all items, so you can crate a pack of cig's where you set durability to 5.0 and it uses 5 dura out of 100, so it matches a 20 pack.

This got a lot of use cases, tryed adding durability to items, but dos not look like it works currently, besides on weapons, hope we can get this for items.

**Comment by LukeWasTakenn** [comment]
You can add degradation to items, not sure if we'd do durability on them.

**Comment by vWernay** [comment]
You can do this using metadata

**Comment by benzon** [comment]
I know degradation can be done that i know, not sure about the other thing tho, you might be right wernay, but when i look true the code, it looks to be handled very wird on items

**Comment by thelindat** [comment]
I may have removed it from the trello since I deemed it unimportant for implementation at the moment, but it will be looked at in the future.

The new server-side item functions should make this fairly easy to do now.
https://github.com/overextended/ox_inventory/blob/main/modules/items/server.lua#L195-L217

Item('cigarattes', function(event, item, inventory, slot, data)
	if event == 'usedItem' then
		-- setup and call some function for editing item durability
	end
end)

You would need to either prevent stacking items with durability, or split the stacks after durability is reduced.

**Comment by benzon** [comment]
Okay super, i think it would be nice to have as a core feature, since i could see more use cases for it, but i understand that it's something that is more down the road.

Thanks Linden ill look in to it, and thanks for adding vending machine support

**Comment by thelindat** [comment]
Using server item hooks.

```lua
Item('jerky', function(event, item, inventory, slot, data)
    if event == 'usedItem' then
        local durability = (inventory.items[slot].metadata.durability or 100) - 25
        Inventory.SetDurability(inventory, slot, durability)
    end
end)
```
