### ISSUE TITLE
Item Durability Beside on weapons

### ISSUE THREAD

**Issue by Daemonns** [overextended/ox_inventory#37]
**Is your feature request related to a problem? Please describe.**
Puting A durability on Items like in the esx_durability if Used 10times or more it will break
Like the item Radio if it used 5 times will break

**Comment by thelindat** [comment]
It is something I plan to do in the future, but I need to work out the best method for it. Items being able to stack could cause issues due to metadata.durability mismatch, then splitting stacks needing to only mess with the durability of one item.

Most likely would only be able to have durability on non-stacking items.

**Comment by Daemonns** [comment]
> It is something I plan to do in the future, but I need to work out the best method for it. Items being able to stack could cause issues due to metadata.durability mismatch, then splitting stacks or using items needing to only mess with the durability of one item.
> 
> Most likely would only be able to have durability on non-stacking items.

how to put a durability on non stackable item?
