### ISSUE TITLE
GiveItem event sometimes nil?

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/ox_inventory#401]
**Describe the bug**
Sometimes when giving an item the `data` is nil, not sure what's causing this apologies.

```lua
[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/inventory/server.lua:774: attempt to index a nil value (local 'data')
[ script:ox_inventory] > handler (@ox_inventory/modules/inventory/server.lua:774)
```

**Additional context**
- **Game Version:** 5129
- **Client:** Production
- **Inventory Build:** f7ce3d9

**Comment by dunak-debug** [comment]
Steps to reproduce?

**Comment by LukeWasTakenn** [comment]
How do you expect us to fix something that happens 'sometimes', especially with no steps to reproduce the issue?

**Comment by DogsGoBark** [comment]
Trying to reproduce this to get the steps for you, apologies.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/147401992-f054a412-98e3-453b-b73a-1edfda3c5910.png)

Error is most likely caused by the event triggering with an invalid slot sent by the client, so `local data = fromInventory.items[slot]` returns nil; this shouldn't even happen so confirmation would be good.
