### ISSUE TITLE
Pincode stash

### ISSUE THREAD

**Issue by MilitaryNekoMaid** [overextended/ox_inventory#492]
So i was thinking it would be nice to have hidden stashes with pincodes 
i don't use gang jobs on my server so i thought that would be the best idea so everyone who has pincode can stash items in it

it would look like: 
Im in place where stash is, i open it and then comes some dialog menu so i have to use pincode that is setup in stashes.lua otherway it doesn't open

simple stuff can be easy done but someone might like it too

**Comment by dunak-debug** [comment]
https://overextended.github.io/ox_inventory/guides/stashes/

**Comment by LukeWasTakenn** [comment]
You should already be able to do this without our direct implementation for it.

Create a stash and then when interacting at a marker or something run `exports.ox_inventory:Keyboard()` to check for a pin or a password, then if correct open the stash, otherwise don't.

https://overextended.github.io/ox_inventory/modules/interface/keyboard/

**Comment by duckysuck** [comment]
> 

this sounds awesome. I may need your help if I get stuck.
