### ISSUE TITLE
Cant use Core Job & qIdentification

### ISSUE THREAD

**Issue by Cloud10Dev** [overextended/ox_inventory#515]
Im trying to use core job for the society management and job center, but i cant access the society management, i press the key and nothing happens and no errors. 

But when i was using old linden inv and legacy, the same one was working. So it might be something i need to change but i dont know what. Could you help?

Also, im tyring to use qId but when i buy it, i get the item and i cant use it, nothing happens and also no erros.. :(

Thank you, keep the great work

**Comment by thelindat** [comment]
Not sure what you expect me to do for core job - couldn't tell you why it doesn't work, and certainly don't have access to the code (I don't need to see it to know it's not worth whatever they sell their shit for).

I don't maintain qidentification and haven't used it since Noms wrote it for linden inventory - better off getting support from whoever is maintaining it now or in the discord support channel.
