### ISSUE TITLE
View inventory

### ISSUE THREAD

**Issue by janwichmann12** [overextended/ox_inventory#757]
You have a bug when you set the rights of the inventory and you want to take items from the other inventory

@ox_inventory/modules/inventory/server.lua:982: attempt to index a nil value (field 'items')

after you want to take it out the inventory hangs and nothing works anymore.

But if you want to remove an item as admin this function should already be available ;) 

![image](https://user-images.githubusercontent.com/92275808/177000102-10f7b9b9-8445-4e8a-9068-7edebb67c602.png)
![image](https://user-images.githubusercontent.com/92275808/177000116-ef887b5f-e027-4971-85d5-c51bce5cfd41.png)
![image](https://user-images.githubusercontent.com/92275808/177000119-f277d25a-7f74-4da4-8179-1bb085607915.png)

**Comment by thelindat** [comment]
what
and you're not even supposed to be _able_ to take items when _viewing_ the inventory

**Comment by janwichmann12** [comment]
I could push around after these settings items I can also like to make a video :D

**Comment by thelindat** [comment]
Trying to decipher this clusterfuck of a post, but it seems like *you've edited ox_inventory* to try and allow moving items during the 'viewinv' command.

That is not an intended feature because of security reasons, and simply disabling the disabled drag options will not magically allow you to drag items.
