### ISSUE TITLE
backup safe item

### ISSUE THREAD

**Issue by Azael62** [overextended/ox_inventory#779]
problem when storing item in the trunk of a parked vehicle possibility of duplicating the item by performing a reboot of the server 

![police](https://user-images.githubusercontent.com/109298739/181128368-8ba02164-5a96-4208-a3d8-95dc9f1ea50e.png)

**Comment by thelindat** [comment]
No information?
Nothing to back up claims of "item duplication"?

When you reboot the server _manually_ no inventory gets saved. txAdmin will save players and stashes when using scheduled restarts.

**Comment by Fellow25** [comment]
Items are not saved in the database. (only on vehicles)

**Comment by thelindat** [comment]
Player items are saved by ESX, not ox_inventory. And they are saved. And I don't see how that duplicates.

**Comment by Azael62** [comment]
https://streamable.com/pnu2oy

**Comment by thelindat** [comment]
> duplicating the item by performing a reboot of the server

Proceeds to show _an empty_ inventory after rebooting the server.

> When you reboot the server manually no inventory gets saved. txAdmin will save players and stashes when using scheduled restarts.

Proceeds to reboot the server with some dumb unauthorised GSP and their panel, thus not triggering the inventory save.

---

Player inventory is saved because you quit the server (ESX saves on quit, using the playerDropped event).
Trunk is not saved, because there's no "restart" event.

Use scheduled restarts, or utilise RCON to trigger commands before a restart (/saveinv).

**Comment by Azael62** [comment]
ok thx bro
