### ISSUE TITLE
I'm facing this issue while entering into the server and also not able to select the character.

### ISSUE THREAD

**Issue by zaneroman** [overextended/ox_inventory#807]
![image](https://user-images.githubusercontent.com/111625284/185914149-6b5ea1d7-0edb-4a18-9a7c-e44dcde4579a.png)

**Comment by thelindat** [comment]
This is an ESX induced issue that was fixed in June.

**Comment by zaneroman** [comment]
Although it was fixed, I'm facing the same error!

**Comment by thelindat** [comment]
> Although it was fixed, I'm facing the same error!

Cool story, but the error is _from_ ESX _not ox inventory_. You can keep saying you get the error, but there's nothing I can change in ox_inventory to stop this from occurring; especially since _it was FIXED IN ESX IN JUNE_ (capitalised so you might read it).

https://github.com/esx-framework/esx-legacy/blob/main/%5Besx%5D/es_extended/server/classes/overrides/oxinventory.lua
