### ISSUE TITLE
I keep getting repeat error in console.

### ISSUE THREAD

**Issue by JuggRichRP** [overextended/ox_inventory#817]
**Describe the bug**
When I start my server, I get this repeat error in my console. Please assist.

**To Reproduce**

**Expected behavior**
I expected my ox inventory to be working :(

**Screenshots**
![image](https://user-images.githubusercontent.com/112251515/187026884-b8966a86-5b9a-40f6-bd22-0124663c8325.png)

**Additional context**
Do I need to update something else? I dont understand why I am getting this repeat error and would just like it fixed because I have tried everything, thank you in advance. 
![image_2022-08-27_065001565](https://user-images.githubusercontent.com/112251515/187026913-aa07288f-a414-422a-83ca-f9c148df493c.png)

**Comment by thelindat** [comment]
> I get this repeat error in my console

I love that I added this error spam bullshit because people would ignore or would not notice the error when it appeared at startup.
And now you're here, ignoring the error spam.

![image](https://user-images.githubusercontent.com/65407488/187079937-bf78c1f2-412f-4175-a3d5-bc5d7b405d43.png)

_You_ made a mistake when modifying data/shops.lua, likely a missing comma inside a table.

**Comment by JuggRichRP** [comment]
Thanks for the help, my bad lmao damn no need to be a bitch ab it

**Comment by JuggRichRP** [comment]
no need to be a dick, but thanks lmao.

**Comment by thelindat** [comment]
> I expected my ox inventory to be working :(

I expected people to understand how to solve their own problems :(
