### ISSUE TITLE
Since the last update we have this error :(

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_inventory#818]
**Describe the bug**
Since the last update 2 days ago we have all the time this problem: 

[  script:es_extended] SCRIPT ERROR: @es_extended/server/functions.lua:264: attempt to call a nil value (field '?')
[  script:es_extended] > ref (@es_extended/server/functions.lua:264)
[  script:es_extended] > [global chunk] (@ox_inventory/server.lua:264)
[  script:es_extended] > handler (@ox_lib/callback/server.lua:73)

**Screenshots**
![image](https://user-images.githubusercontent.com/35350615/187044922-5daae609-667b-44fd-bd3f-f77bd9d1f08c.png)

**Comment by thelindat** [comment]
People kept complaining about items not working, so ESX.UseItem is _always_ called if none of the other requirements to use internal stuff are met.

That also means older versions of ESX will throw errors because they don't check if the item is usable.

https://github.com/esx-framework/esx-legacy/blob/main/%5Besx%5D/es_extended/server/functions.lua#L312-L326

**Comment by soniXx123** [comment]
ok understand and what about this? since the last update :( 

![image](https://user-images.githubusercontent.com/35350615/187092661-264cd303-ad7a-4fa8-94d8-aa629ed73e0b.png)
