### ISSUE TITLE
To Change the keybinds to Tab Like other games 

### ISSUE THREAD

**Issue by Noorulhuda69** [overextended/ox_inventory#827]
I'm was frustrated about inventory keybinds, bcoz it's not changing i even tried on inventory.cfg, module/init.lua and client.lua,

There should be some thing in lua to change the keybinds like how we do on other scripts

**Comment by thelindat** [comment]
Because FiveM handles keybinds, and if you want to modify an existing keybind then you need to edit it _in game_. I'm honestly tempted to remove it _because_ people don't understand how FiveM keybinds work.

![image](https://user-images.githubusercontent.com/65407488/188230030-aafad7ac-9090-4765-8743-7c5e5364f8b6.png)
